name: footprint
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - rasterio
  - scikit-learn
  - matplotlib
  - folium
  - imageio
  - pip:
    - earthengine-api
    - codecarbon
    - torch
    - torchvision
    - scikit-image
